# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Eltrin
tagline:             'Gaming.  Simplified.'
description:         ''
url:                 http://eltrin.com
baseurl:             'eltrin.com'
paginate:            5

# About/contact
author:
  name:              Clifton Marien
  url:               
  email:             

# Custom vars
version:             1.0.0
